### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.pdfbox.pdmodel.PDDocument.setVersion(F)V

### ISSUE THREAD

**Issue by sunnyshergill** [danfickle/openhtmltopdf#101]
hi, 
iam getting this error everytime i try to create pdf. I have added **"openhtmltopdf-pdfbox.jar"** and **"openhtmltopdf-core.jar".**
"Exception in thread "main" java.lang.NoSuchMethodError: org.apache.pdfbox.pdmodel.PDDocument.setVersion(F)V
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.<init>(PdfBoxRenderer.java:175)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.buildPdfRenderer(PdfRendererBuilder.java:106)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:84)
	at Email2PDF.exportToPdfBox(Email2PDF.java:87)
	at Email2PDF.main(Email2PDF.java:30)
"

**Comment by rototor** [comment]
Are you using maven? It seems you may have a wrong version of PDFBox in your classpath. Maybe you have PDFBox 1.8 in your classpath? The current PDFBox version is 2.0.6.

**Comment by danfickle** [comment]
Assumed solved. Re-open if required.
