### ISSUE TITLE
NPE if the name attribute for form element is not set

### ISSUE THREAD

**Issue by mmatecki** [danfickle/openhtmltopdf#151]
Hello,
There's NPE if HTML form element doesn't have `name` attribute set.

Example HTML:
```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">    
  </head>
  <body>
  <form>
    <input type="text"/>
  </form>
  </body>
</html>
```
Exception:
```
java.lang.NullPointerException
	at com.openhtmltopdf.pdfboxout.PdfBoxForm$Field.access$602(PdfBoxForm.java:78)
	at com.openhtmltopdf.pdfboxout.PdfBoxForm.processTextControl(PdfBoxForm.java:435)
	at com.openhtmltopdf.pdfboxout.PdfBoxForm.process(PdfBoxForm.java:803)
	at com.openhtmltopdf.pdfboxout.PdfBoxOutputDevice.processControls(PdfBoxOutputDevice.java:379)
	at com.openhtmltopdf.pdfboxout.PdfBoxOutputDevice.finish(PdfBoxOutputDevice.java:1001)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.writePDF(PdfBoxRenderer.java:607)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:546)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:485)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:481)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:86)
```

Regards,
Maciek.

**Comment by iristic** [comment]
two years too late... but your input element needs to have name attribute set in order not to get NPE.
