### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.pdfbox.pdmodel.PDDocument.getPage( )

### ISSUE THREAD

**Issue by asdf5252** [danfickle/openhtmltopdf#175]
Hello , 
I am getting this error when I am trying to get the page content through PDDocument
I am having maven dependency of PDFBox version 2.0.8
```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.pdfbox.pdmodel.PDDocument.getPage(I)Lorg/apache/pdfbox/pdmodel/PDPage;
	at com.check.all.check.c1.isScan(c1.java:82)
	at com.check.all.check.c1.checkpdf(c1.java:173)
	at com.check.all.check.c1.main(c1.java:46)
```

**Comment by danfickle** [comment]
There could be a couple of reasons:
+ Another dependency is in turn depending on a different version of PDFBOX which is taking precedence.
+ Maven local jar is corrupted. You [could try deleting the PDFBOX directory in maven](https://stackoverflow.com/questions/15358851/how-to-remove-jar-file-from-local-maven-repository-which-was-added-with-install).

**Comment by asdf5252** [comment]
Hello @danfickle 

Yes, it is due to corrupted jar . Thankyou
