### ISSUE TITLE
App Engine support?

### ISSUE THREAD

**Issue by achuinard** [danfickle/openhtmltopdf#179]
Any chance this works on App Engine under the Java 8 runtime? If so should the README be updated? I can create a PR for the README if @danfickle says it runs.

Java 8 has no restrictions so it seems like it would run on App Engine...

**Comment by danfickle** [comment]
Thanks @achuinard 

I've changed the readme. I'll leave this issue open until someone has confirmed that it works.

**Comment by Rob46** [comment]
Yep, it works. No issues yet. Java App Engine Standard Environ 8.

**Comment by hehsiao** [comment]
It does works, but I also got this on the first call, subsequent call on the same instance works fine tho.

```
2018-05-23 16:28:56.478 PDT org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>: Building on-disk font cache, this may take a while (FileSystemFontProvider.java:224)
2018-05-23 16:28:56.479 PDT org.apache.pdfbox.pdmodel.font.FileSystemFontProvider saveDiskCache: Could not write to font cache (FileSystemFontProvider.java:349)
java.io.FileNotFoundException: /base/data/home/.pdfbox.cache (Read-only file system)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at org.apache.pdfbox.pdmodel.font.FileSystemFontProvider.saveDiskCache(FileSystemFontProvider.java:290)
	at org.apache.pdfbox.pdmodel.font.FileSystemFontProvider.<init>(FileSystemFontProvider.java:226)
	at org.apache.pdfbox.pdmodel.font.FontMapperImpl$DefaultFontProvider.<clinit>(FontMapperImpl.java:130)
	at org.apache.pdfbox.pdmodel.font.FontMapperImpl.getProvider(FontMapperImpl.java:149)
	at org.apache.pdfbox.pdmodel.font.FontMapperImpl.findFont(FontMapperImpl.java:413)
	at org.apache.pdfbox.pdmodel.font.FontMapperImpl.findFontBoxFont(FontMapperImpl.java:376)
	at org.apache.pdfbox.pdmodel.font.FontMapperImpl.getFontBoxFont(FontMapperImpl.java:350)
	at org.apache.pdfbox.pdmodel.font.PDType1Font.<init>(PDType1Font.java:145)
	at org.apache.pdfbox.pdmodel.font.PDType1Font.<clinit>(PDType1Font.java:79)
	at com.openhtmltopdf.pdfboxout.PdfBoxFontResolver.addCourier(PdfBoxFontResolver.java:397)
	at com.openhtmltopdf.pdfboxout.PdfBoxFontResolver.createInitialFontMap(PdfBoxFontResolver.java:372)
	at com.openhtmltopdf.pdfboxout.PdfBoxFontResolver.<init>(PdfBoxFontResolver.java:58)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.<init>(PdfBoxRenderer.java:205)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.buildPdfRenderer(PdfRendererBuilder.java:106)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:84)
	...
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
	at java.lang.Thread.run(Thread.java:745)
2018-05-23 16:28:56.481 PDT org.apache.pdfbox.pdmodel.font.FileSystemFontProvider saveDiskCache: Installed fonts information will have to be reloaded for each start (FileSystemFontProvider.java:350)
2018-05-23 16:28:56.481 PDT org.apache.pdfbox.pdmodel.font.FileSystemFontProvider saveDiskCache: You can assign a directory to the 'pdfbox.fontcache' property (FileSystemFontProvider.java:351)
2018-05-23 16:28:56.483 PDT org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>: Finished building on-disk font cache, found 0 fonts (FileSystemFontProvider.java:227)
2018-05-23 16:28:56.485 PDT org.apache.pdfbox.pdmodel.font.PDType1Font <init>: Using fallback font LiberationSans for base font Times-Roman (PDType1Font.java:161)
2018-05-23 16:28:56.486 PDT org.apache.pdfbox.pdmodel.font.PDType1Font <init>: Using fallback font LiberationSans for base font Times-Bold (PDType1Font.java:161)
2018-05-23 16:28:56.487 PDT org.apache.pdfbox.pdmodel.font.PDType1Font <init>: Using fallback font LiberationSans for base font Times-Italic (PDType1Font.java:161)
2018-05-23 16:28:56.488 PDT org.apache.pdfbox.pdmodel.font.PDType1Font <init>: Using fallback font LiberationSans for base font Times-BoldItalic (PDType1Font.java:161)
2018-05-23 16:28:56.488 PDT org.apache.pdfbox.pdmodel.font.PDType1Font <init>: Using fallback font LiberationSans for base font Helvetica (PDType1Font.java:161)
2018-05-23 16:28:56.489 PDT org.apache.pdfbox.pdmodel.font.PDType1Font <init>: Using fallback font LiberationSans for base font Helvetica-Bold (PDType1Font.java:161)
2018-05-23 16:28:56.490 PDT org.apache.pdfbox.pdmodel.font.PDType1Font <init>: Using fallback font LiberationSans for base font Helvetica-Oblique (PDType1Font.java:161)
2018-05-23 16:28:56.491 PDT org.apache.pdfbox.pdmodel.font.PDType1Font <init>: Using fallback font LiberationSans for base font Helvetica-BoldOblique (PDType1Font.java:161)
2018-05-23 16:28:56.492 PDT org.apache.pdfbox.pdmodel.font.PDType1Font <init>: Using fallback font LiberationSans for base font Courier (PDType1Font.java:161)
2018-05-23 16:28:56.492 PDT org.apache.pdfbox.pdmodel.font.PDType1Font <init>: Using fallback font LiberationSans for base font Courier-Bold (PDType1Font.java:161)
2018-05-23 16:28:56.493 PDT org.apache.pdfbox.pdmodel.font.PDType1Font <init>: Using fallback font LiberationSans for base font Courier-Oblique (PDType1Font.java:161)
2018-05-23 16:28:56.494 PDT org.apache.pdfbox.pdmodel.font.PDType1Font <init>: Using fallback font LiberationSans for base font Courier-BoldOblique (PDType1Font.java:161)
2018-05-23 16:28:56.495 PDT org.apache.pdfbox.pdmodel.font.PDType1Font <init>: Using fallback font LiberationSans for base font Symbol (PDType1Font.java:161)
2018-05-23 16:28:56.496 PDT org.apache.pdfbox.pdmodel.font.PDType1Font <init>: Using fallback font LiberationSans for base font ZapfDingbats (PDType1Font.java:161)
```

**Comment by ZiLongLing** [comment]
When in HTML img SRC is Base64,img is not printed

**Comment by danfickle** [comment]
Hi @ZiLongLing , Does it work outside app engine? What version?
