### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by valeriegrace** [danfickle/openhtmltopdf#216]
Hi,
Is there a tutorial or Java doc I can use to see how to convert HTML to PDF using openpdftohtml. 
I have a simple html - 
<html>
<head></head>
<body>Hello World</body>
</html>
  
Below is the error I got. I used PdfRenderBuilder as shown in the example - 

com.openhtmltopdf.load INFO:: SAX XMLReader in use (parser): com.sun.org.apache.xerces.internal.parsers.SAXParser
com.openhtmltopdf.load INFO:: SAX XMLReader in use (parser): com.sun.org.apache.xerces.internal.parsers.SAXParser
com.openhtmltopdf.exception WARNING:: Unhandled exception. Failed on configuring SAX to DOM transformer.
Exception in thread "main" com.openhtmltopdf.util.XRRuntimeException: Failed on configuring SAX to DOM transformer.
	at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:266)
	at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.access$100(XMLResource.java:168)
	at com.openhtmltopdf.resource.XMLResource.load(XMLResource.java:81)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.setDocumentFromString(PdfBoxRenderer.java:239)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.<init>(PdfBoxRenderer.java:168)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.buildPdfRenderer(PdfRendererBuilder.java:51)
	at com.fedex.templatemaker.util.Test.renderPDF(Test.java:54)
	at com.fedex.templatemaker.util.Test.main(Test.java:45)
Caused by: java.lang.NullPointerException: SharedContext must be registered in renderer.
	at com.openhtmltopdf.util.ThreadCtx$ThreadData.sharedContext(ThreadCtx.java:32)
	at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:245)
	... 7 more

**Comment by danfickle** [comment]
Hi @valeriegrace 

Here is the simplest possible example. Can you post the code you tried in a code block (four back ticks at start and end of code) so I can fix the documentation or project as required? Thanks.

While there is no java docs online you can read the source for the builder at the following two files. It is pretty well doced.

https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-core/src/main/java/com/openhtmltopdf/outputdevice/helper/BaseRendererBuilder.java

https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfRendererBuilder.java


````java
	public static void main(String... args) throws Exception {
		
		try (FileOutputStream os = new FileOutputStream("/Users/me/Documents/pdf-issues/output/mytest-216.pdf")) {
			PdfRendererBuilder builder = new PdfRendererBuilder();
			builder.withUri("file:///Users/me/Documents/pdf-issues/issue-216.htm");
			builder.toStream(os);
			builder.run();
		}
	}
````
