### ISSUE TITLE
java.io.IOException: The TrueType font does not contain a 'cmap' table

### ISSUE THREAD

**Issue by mapleLeat** [danfickle/openhtmltopdf#234]
R14 version, generating pdf custom font error, but PDF font displayed correctly

```
java.io.IOException: The TrueType font does not contain a 'cmap' table
	at org.apache.fontbox.ttf.TrueTypeFont.getUnicodeCmap(TrueTypeFont.java:477)
	at org.apache.fontbox.ttf.TrueTypeFont.getUnicodeCmap(TrueTypeFont.java:460)
	at org.apache.fontbox.ttf.TTFSubsetter.<init>(TTFSubsetter.java:90)
	at org.apache.pdfbox.pdmodel.font.TrueTypeEmbedder.subset(TrueTypeEmbedder.java:318)
	at org.apache.pdfbox.pdmodel.font.PDType0Font.subset(PDType0Font.java:162)
	at com.openhtmltopdf.pdfboxout.PdfBoxFontResolver.close(PdfBoxFontResolver.java:86)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.cleanup(PdfBoxRenderer.java:850)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.close(PdfBoxRenderer.java:872)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:37)
	at com.promise.actual.deisgn.pdf.PdfTemplate.htmlToPdf(PdfTemplate.java:432)
	at com.promise.actual.deisgn.pdf.PdfTemplate.createSamplePdf(PdfTemplate.java:246)

	at com.promise.actual.deisgn.pdf.PdfTemplate.drawPdf(PdfTemplate.java:212)
	at com.promise.actual.deisgn.pdf.PdfTemplate.createPDF(PdfTemplate.java:127)
	at com.promise.actual.deisgn.pdf.PdfTemplate.<init>(PdfTemplate.java:78)
	at com.promise.redis.notification.ExpiredAction.createPdf(ExpiredAction.java:68)
	at com.promise.redis.notification.OrderSubscribe.onPMessage(OrderSubscribe.java:47)
	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:145)
	at redis.clients.jedis.JedisPubSub.proceedWithPatterns(JedisPubSub.java:96)
	at redis.clients.jedis.Jedis.psubscribe(Jedis.java:2769)
	at com.promise.redis.notification.RedisInitSubscrib.afterPropertiesSet(RedisInitSubscrib.java:22)
	at com.promise.redis.notification.RedisInitSubscrib.run(RedisInitSubscrib.java:29)
```

**Comment by mapleLeat** [comment]
Duplicate of #224
