### ISSUE TITLE
java.lang.NullPointerException: null -> PdfBoxTextRenderer.getWidth(PdfBoxTextRenderer.java:300)

### ISSUE THREAD

**Issue by taras19921** [danfickle/openhtmltopdf#267]
I'm using 0.0.1-RC15 version. I am getting the following error during generating PDF:

> java.lang.NullPointerException: null
	at com.openhtmltopdf.pdfboxout.PdfBoxTextRenderer.getWidth(PdfBoxTextRenderer.java:300)
	at com.openhtmltopdf.render.InlineBox.getSpaceWidth(InlineBox.java:221)
	at com.openhtmltopdf.render.InlineBox.calcMinWidthFromWordLength(InlineBox.java:238)
	at com.openhtmltopdf.render.InlineBox.calcMinMaxWidth(InlineBox.java:378)
	at com.openhtmltopdf.render.BlockBox.calcMinMaxWidthInlineChildren(BlockBox.java:1748)
	at com.openhtmltopdf.render.BlockBox.calcMinMaxWidth(BlockBox.java:1624)
	at com.openhtmltopdf.render.BlockBox.calcShrinkToFitWidth(BlockBox.java:1501)
	at com.openhtmltopdf.render.BlockBox.calcShrinkToFitWidthIfNeeded(BlockBox.java:976)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:869)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:823)
	at com.openhtmltopdf.layout.InlineBoxing.layoutInlineBlockContent(InlineBoxing.java:426)
	at com.openhtmltopdf.layout.InlineBoxing.layoutContent(InlineBoxing.java:317)
	at com.openhtmltopdf.render.BlockBox.layoutInlineChildren(BlockBox.java:1068)
	at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:1049)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:906)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:823)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:321)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:299)
	at com.openhtmltopdf.layout.BlockBoxing.layoutContent(BlockBoxing.java:90)
	at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:1052)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:906)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:823)
	at com.openhtmltopdf.layout.Layer.layoutAbsoluteChild(Layer.java:1014)
	at com.openhtmltopdf.layout.Layer.layoutAbsoluteChildren(Layer.java:949)
	at com.openhtmltopdf.layout.Layer.finish(Layer.java:935)
	at com.openhtmltopdf.layout.LayoutContext.popLayer(LayoutContext.java:306)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:948)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:823)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.layout(PdfBoxRenderer.java:333)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:40)

I can't figure out what's wrong.

**Comment by syjer** [comment]
hi @taras19921 , could you provide the file to reproduce the error? Or at least, a minimal one so we can reproduce it?

**Comment by taras19921** [comment]
I've found the problem. Problem was in access to image on remote server.
