### ISSUE TITLE
If <head> tags are missing when PDF/UA compliance is enabled, it throws an IllegalArgumentException

### ISSUE THREAD

**Issue by SomeDeveloper13** [danfickle/openhtmltopdf#332]
When the Header is missing, it fails to generate the PDF or return a useful error message.
When other PDF/UA components are missing, it is able to generate the PDF.

### Code:
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        PdfRendererBuilder builder = new PdfRendererBuilder();

        try {
            builder.useUriResolver(new CustomHttpUrlResolver(appConfig));
            builder.useHttpStreamImplementation(new CustomHttpStreamFactory(appConfig));
            builder.useFastMode();
            //builder.testMode(true);
            builder.usePdfUaAccessbility(true);
            builder.useFont(new File(getClass().getResource("/calibri.ttf").toURI()), "CalibriFont");
            builder.withHtmlContent(html, "/");
            builder.toStream(os);
            builder.run();

        } catch (Exception ex) {
            logger.error("Unable to convert HTML to PDF.", ex);
            return new ByteArrayResponse(null, "Unable to convert HTML to PDF: "+ex.getMessage());
        }

### Working HTML:
    <html><head><title>Form 39</title></head><body><p>This is a test HTML page</p></body></html>

### Failing HTML:
    <html></head><body><p>This is a test HTML page</p></body></html>

### Stack Trace:
	2019-02-27 10:06:37 ERROR g.d.u.e.j.service.HtmlToPdfService - Unable to convert HTML to PDF.
	java.lang.IllegalArgumentException: Value given is not allowed for the Text type : 'null'
		at org.apache.xmpbox.type.TextType.setValue(TextType.java:68)
		at org.apache.xmpbox.type.AbstractSimpleProperty.<init>(AbstractSimpleProperty.java:59)
		at org.apache.xmpbox.type.TextType.<init>(TextType.java:53)
		at org.apache.xmpbox.type.TypeMapping.createText(TypeMapping.java:404)
		at org.apache.xmpbox.type.AbstractStructuredType.createTextType(AbstractStructuredType.java:155)
		at org.apache.xmpbox.schema.XMPSchema.setUnqualifiedLanguagePropertyValue(XMPSchema.java:1057)
		at org.apache.xmpbox.schema.DublinCoreSchema.setTitle(DublinCoreSchema.java:361)
		at org.apache.xmpbox.schema.DublinCoreSchema.setTitle(DublinCoreSchema.java:371)
		at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.addPdfUaXMPSchema(PdfBoxRenderer.java:707)
		at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.writePDFFast(PdfBoxRenderer.java:593)
		at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPdfFast(PdfBoxRenderer.java:543)
		at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:461)
		at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:398)
		at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:380)
		at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:41)
		at my.service.HtmlToPdfService.convertHtmlToPdf(HtmlToPdfService.java:46)
		at my.controller.WebController.htmlToPdf(WebController.java:74)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
		at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
		at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891)
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
		at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:981)
		at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:884)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:858)
		at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:71)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
		at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:166)
		at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:133)
		at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:165)
		at my.controller.WebControllerTest2.htmlToPdfTest(WebControllerTest2.java:52)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
		at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
		at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
		at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
		at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
		at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
		at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
		at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
		at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

**Comment by danfickle** [comment]
Thanks @SomeDeveloper13. Although, you still have to provide a body font.
