### ISSUE TITLE
I am getting the following error while rendering the pdf from given html.

### ISSUE THREAD

**Issue by nagababuballa** [danfickle/openhtmltopdf#345]
org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified.

18:49:51.968 [taskExecutor-2] ERROR com.spl.focal.appContext.app.logic.EmployeePDFProcessing - Exception occured in the method writePdfFil
org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 
	at org.apache.xerces.dom.CoreDocumentImpl.createAttribute(Unknown Source) ~[xercesImpl-2.10.0.jar:?]
	at org.apache.xerces.dom.ElementImpl.setAttribute(Unknown Source) ~[xercesImpl-2.10.0.jar:?]
	at com.openhtmltopdf.DOMBuilder.createDOM(DOMBuilder.java:101) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
	at com.openhtmltopdf.DOMBuilder.createDOM(DOMBuilder.java:108) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
	at com.openhtmltopdf.DOMBuilder.createDOM(DOMBuilder.java:108) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
	at com.openhtmltopdf.DOMBuilder.createDOM(DOMBuilder.java:108) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
	at com.openhtmltopdf.DOMBuilder.createDOM(DOMBuilder.java:108) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
	at com.openhtmltopdf.DOMBuilder.createDOM(DOMBuilder.java:108) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
	at com.openhtmltopdf.DOMBuilder.createDOM(DOMBuilder.java:108) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
taskExecutor-1) TIME: parse stylesheets  0ms
	at com.openhtmltopdf.DOMBuilder.createDOM(DOMBuilder.java:108) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
	at com.openhtmltopdf.DOMBuilder.createDOM(DOMBuilder.java:108) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
(taskExecutor-1) media = print
	at com.openhtmltopdf.DOMBuilder.createDOM(DOMBuilder.java:108) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
	at com.openhtmltopdf.DOMBuilder.createDOM(DOMBuilder.java:108) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
	at com.openhtmltopdf.DOMBuilder.createDOM(DOMBuilder.java:108) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
taskExecutor-1) Requesting stylesheet: file:/D:/pdf-changes/client-8.5/focal/src/main/webapp/static/text-editor/css/performanceForm.css
	at com.openhtmltopdf.DOMBuilder.createDOM(DOMBuilder.java:108) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
	at com.openhtmltopdf.DOMBuilder.createDOM(DOMBuilder.java:72) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
	at com.openhtmltopdf.DOMBuilder.jsoup2DOM(DOMBuilder.java:46) ~[openhtmltopdf-jsoup-dom-converter-0.0.1-RC17.jar:?]
	at com.spl.focal.appContext.app.logic.EmployeePDFProcessing.writePdfFileToArchiveDir(EmployeePDFProcessing.java:57) ~[classes/:?]
	at com.spl.focal.appContext.app.logic.EmployeePDFProcessing.processPdfForReport(EmployeePDFProcessing.java:50) ~[classes/:?]
	at com.spl.focal.appContext.app.logic.EmployeePrintForm.processpdf(EmployeePrintForm.java:461) [classes/:?]

**Comment by danfickle** [comment]
I think this is probably because the [rules for a XML attribute name](https://www.w3.org/TR/xml/#NT-NameChar) are tighter than the rules for an HTML5 attribute name, though i am not sure which character is the problem. Look for characters outside a to z and 0 - 9 in attribute names.

Although I suspect that it won't fix this problem, I have deprecated the jsoup-dom-converter module because Jsoup now has this functionality inbuilt. With Jsoup, the code is as simple as:
````java
org.w3c.dom.Document doc = new W3CDom().fromJsoup(doc);
````
where `doc` is a Jsoup parsed `Document`.

**Comment by danfickle** [comment]
Assumed solved, please re-open if required.

**Comment by nagababuballa** [comment]
Hi Danfickle,

Thanks for your prompt response. the underlying problem is not because of the open html plugin we are internally using the text-editor plugin for formatting and it is not generating the well formed html i solved that problem using java tidy tool.
Only problem which i am right now facing is font tags are not rendering correctly.
if assume like <font color="red">hai</font>
'hai' doesn't appears in red color in pdf if you give like <span style="color:red">hai</span> then it is working fine.
but my text-editor is generating font tags while applying the colour to text.
Could you please notice it and let me know the solution.

Thanks.

**Comment by nagababuballa** [comment]
Hi Danfickle,

Thanks for your prompt response. the underlying problem is not because of the open html plugin we are internally using the text-editor plugin for formatting and it is not generating the well formed html i solved that problem using java tidy tool.
Only problem which i am right now facing is font tags are not rendering correctly.
if assume like '<font color="red">hai</font>
'hai' doesn't appears in red color in pdf if you give like '<span style="color:red;">hai</span> then it is working fine.
but my text-editor is generating font tags while applying the colour to text.
Could you please notice it and let me know the solution.

Thanks.

**Comment by danfickle** [comment]
Hi @nagababuballa,

The font tag has been obsolete for twenty years! Also, this project is primarily about taking templates combined with text provided by users and rendering to PDF. Feeding it user provided untrusted HTML/XML may not be 100% secure.

If you must use this particular HTML editor, I would use Jsoup to fix the generated HTML and sanitize it, for example, by allowing only a few tags and attributes that you expect. To fix the font tag, you could put the color attribute in a proper style attribute.
