### ISSUE TITLE
problem when generate pdf

### ISSUE THREAD

**Issue by ellouze** [danfickle/openhtmltopdf#371]
org.xml.sax.SAXNotRecognizedException: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
	at org.apache.xerces.parsers.AbstractSAXParser.setFeature(Unknown Source)
	at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.setXmlReaderSecurityFeatures(XMLResource.java:178)
	at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:237)
	at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.access$100(XMLResource.java:168)
	at com.openhtmltopdf.resource.XMLResource.load(XMLResource.java:81)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.setDocumentFromStringP(PdfBoxRenderer.java:292)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.<init>(PdfBoxRenderer.java:234)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.buildPdfRenderer(PdfRendererBuilder.java:63)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:39)
	at .export.pdf.GeneratePdfFile.generatePdf(GeneratePdfFile.java:136)

**Comment by danfickle** [comment]
Hi @ellouze,

This typically means you have an older version of xerces on your classpath. The good news is that if you are not letting users provide XML (not recommended anyway) you can safely ignore this warning.

**Comment by danfickle** [comment]
Assumed solved, please reopen if required.
