### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/xmpbox/type/AbstractField

### ISSUE THREAD

**Issue by ewashchysion** [danfickle/openhtmltopdf#377]
I am getting this error when calling run() on the PdfRendererBuilder. I have downloaded the required jars and have them in my classpath. What do I need to do to resolve this issue?
Code:
        PdfRendererBuilder builder = new PdfRendererBuilder();
        builder.useFastMode();
        builder.withHtmlContent(doc.getTextContent(), doc.getBaseURI());
        builder.toStream(out);
        builder.run();
Stack trace:
Caused by: java.lang.NoClassDefFoundError: org/apache/xmpbox/type/AbstractField
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.buildPdfRenderer(PdfRendererBuilder.java:63) ~[openhtmltopdf-pdfbox-1.0.0.jar:na]
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:39) ~[openhtmltopdf-pdfbox-1.0.0.jar:na]

**Comment by zimmi** [comment]
Sounds like you are missing `xmpbox.jar` on your classpath. I would recommend using Maven / Gradle so future dependencies are resolved automatically. Maven configuration can be found in the [Integration Guide](https://github.com/danfickle/openhtmltopdf/wiki/Integration-Guide).
