### ISSUE TITLE
.continued:before makes Errors

### ISSUE THREAD

**Issue by moccand** [danfickle/openhtmltopdf#461]
juste adding this in the HTML styles :  

```
.continued:before {
    /**
     * For repeated table headers (<thead> elements), show " - Continued"
     * before each table header repeat on subsequent (not initial) pages.
     * See https://github.com/danfickle/openhtmltopdf/pull/32
     */
    content: " - Continued";
    visibility: -fs-table-paginate-repeated-visible;
}
```

makes an error : 

```
com.openhtmltopdf.load INFO:: SAX XMLReader in use (parser): com.sun.org.apache.xerces.internal.parsers.SAXParser
com.openhtmltopdf.load INFO:: SAX XMLReader in use (parser): com.sun.org.apache.xerces.internal.parsers.SAXParser
com.openhtmltopdf.load INFO:: Le type d'ÚlÚment "thead" doit se terminer par la balise de fin correspondante "</thead>".
ERROR:  'Le type d'élément "thead" doit se terminer par la balise de fin correspondante "</thead>".'
com.openhtmltopdf.exception WARNING:: Unhandled exception. Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 277; columnNumber: 5; Le type d'ÚlÚment "thead" doit se terminer par la balise de fin correspondante "</thead>".
com.openhtmltopdf.util.XRRuntimeException: Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 277; columnNumber: 5; Le type d'élément "thead" doit se terminer par la balise de fin correspondante "</thead>".
        at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:274)
        at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.access$100(XMLResource.java:168)
        at com.openhtmltopdf.resource.XMLResource.load(XMLResource.java:81)
        at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.setDocumentFromStringP(PdfBoxRenderer.java:293)
        at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.<init>(PdfBoxRenderer.java:235)
        at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.buildPdfRenderer(PdfRendererBuilder.java:63)
        at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:39)


```
The class is not used yet in the HTML page Tables.
I already have this style workin before addint the 'continued'
```
table {
   -fs-table-paginate: paginate;
}

```
Some of my Tables (the short and simple ones) don't have Header and Footers.
The tables that should be paginated are mostly nested ones.

**Comment by leonorader** [comment]
@moccand Could you please share the html code? 

I think the problem is not related to the PR and styles you mentioned, but simply that there is an ending </thead> missing from your html code.

**Comment by moccand** [comment]
here is a download link : 

https://wetransfer.com/downloads/3ebe91acb21e64a8a383e7e17731c2c520200322122449/996761b373a6dd8d237aaf741e81f80220200322122504/0729e4

**Comment by leonorader** [comment]
@moccand 
So I checked it locally and it worked for me, no exception, see the attached image (added a few more rows to that table):

![image](https://user-images.githubusercontent.com/6597652/77250068-aed59e80-6c45-11ea-9750-1485f4c21277.png)

I used openhtmltopdf version 1.0.2, which one did you use?

**Comment by moccand** [comment]
I also use 1.0.2

didi you uncomment this : 

/* Ticket GitHub pour faire marcher ce truc
.continued:before {
    content: " - Continued";
    visibility: -fs-table-paginate-repeated-visible;
}
*/

**Comment by leonorader** [comment]
Oh, now I see what happened here. 
So in your question you had this:
``` 
.continued:before {
    /**
     * For repeated table headers (<thead> elements), show " - Continued"
     * before each table header repeat on subsequent (not initial) pages.
     * See https://github.com/danfickle/openhtmltopdf/pull/32
     */
    content: " - Continued";
    visibility: -fs-table-paginate-repeated-visible;
}
```
And this piece of code contains `<thead>`, so the parser complained about it.

But if you remove (as I uncommented and tried so) the comments, it is all good:
```
.continued:before {
    content: " - Continued";
    visibility: -fs-table-paginate-repeated-visible;
}
```

Will you please try?

**Comment by moccand** [comment]
It Works ! Thanks !
