### ISSUE TITLE
IndexOutOfBoundsException when rendering PDF/A-1 with page number

### ISSUE THREAD

**Issue by PetroProtsyk** [danfickle/openhtmltopdf#488]
I am using the following code to render a pdf with page numbers:

```java       
package org.example;

import java.io.FileOutputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;

public class App {
    public static void main(String[] args) throws Exception {
        try (OutputStream os = new FileOutputStream("output.pdf")) {
            PdfRendererBuilder builder = new PdfRendererBuilder();
            // The following line causes exception:
            builder.usePdfAConformance(PdfRendererBuilder.PdfAConformance.PDFA_1_A);
            String content = new String(Files.readAllBytes(Paths.get(args[0])));
            builder.withHtmlContent(content, ".");
            builder.toStream(os);
            builder.run();
        }
    }
}
```

```html
<html>
<head>
<style>
@page {
	size: a4;
	margin: 50px;
	@bottom-center {
	  content: 'You are on ' counter(page) ' of ' counter(pages);	
	}
}
</style>
</head>
<body>
 <div>
   This is my page
 </div>
</body>
</html>
```
and it fails with the following error message:

```txt
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:458)
        at com.openhtmltopdf.pdfboxout.PdfBoxSlowOutputDevice.drawString(PdfBoxSlowOutputDevice.java:376)
        at com.openhtmltopdf.pdfboxout.PdfBoxTextRenderer.drawString(PdfBoxTextRenderer.java:51)
```

This only happens when I use `@bottom-center` together with `builder.usePdfAConformance(PdfRendererBuilder.PdfAConformance.PDFA_1_A)`

**Comment by danfickle** [comment]
Hi @PetroProtsyk,

1. Please `useFastMode()` on the builder.
2. PDF/a standards prohibit use of built in fonts so you must provide your own and specify its use in the `@bottom-center` and on the body element.

**Comment by PetroProtsyk** [comment]
Thank you, I have fixed the problem by specifying a font in `@bottom-center` like this:
```html
@font-face {
    font-family: 'sans';
    src: url('file:///.../fonts/OpenSans-Regular.ttf');
}
@page {
	size: a4;
	margin: 50px;
	@bottom-center {
	  font: 11pt 'sans';
	  content: 'You are on ' counter(page) ' of ' counter(pages);	
	}
}
```
