### ISSUE TITLE
Outputting an image fails due to IndexOutofBoundsException

### ISSUE THREAD

**Issue by payparr** [danfickle/openhtmltopdf#497]
Hey all,
I am trying to export some html as an image using the following code:
         
          DefaultPageProcessor processor = new DefaultPageProcessor(
                    pageNumber ->
                            new FileOutputStream(
                                    "./images/%page-number%.png"
                                            .replace("%page-number%", String.valueOf(pageNumber))),
                    BufferedImage.TYPE_3BYTE_BGR, "png");

            Graphics2D g2d = processor.createLayoutGraphics();

            String html =
               "<html lang=\"en\"><body><div>"
                  + dataPoints.get(0).getValue()
                  + "</div></body>\n"
                  + "</html>";
            new Java2DRendererBuilder()
                    .withHtmlContent(html, "/")
                    .useLayoutGraphics(g2d)
                    .toSinglePage(processor)
                    .runFirstPage();
            g2d.dispose();

When this code runs, this results in the following IndexOutOfBounds exception, which seems due to it expecting a font to be present for a given text run when there is not one.

`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.openhtmltopdf.java2d.Java2DTextRenderer.getWidth(Java2DTextRenderer.java:294)
	at com.openhtmltopdf.layout.Breaker.doBreakText(Breaker.java:432)
	at com.openhtmltopdf.layout.Breaker.doBreakText(Breaker.java:209)
	at com.openhtmltopdf.layout.Breaker.breakText(Breaker.java:119)
	at com.openhtmltopdf.layout.InlineBoxing.layoutText(InlineBoxing.java:1083)
	at com.openhtmltopdf.layout.InlineBoxing.startInlineText(InlineBoxing.java:388)
	at com.openhtmltopdf.layout.InlineBoxing.layoutContent(InlineBoxing.java:186)
...`

Thanks!

**Comment by danfickle** [comment]
That's right, you need a font. If you want to use whatever is available on your machine:
`builder.useEnvironmentFonts(true)` 

Otherwise, you can provide a font with the builder or a `@font-face` rule. Remember to specify its use on the body element.

**Comment by payparr** [comment]
The `useEnvironmentFonts` approach worked. Thanks!
