### ISSUE TITLE
resolveFont NullPointerException Exception

### ISSUE THREAD

**Issue by pipti** [danfickle/openhtmltopdf#546]
use openhtmltopdf->openhtmltopdf-examples module->FreeMakerGeneratorTest.java testFreeMakerGenerator ,modify the html code ，when test the method，exception happened，I do not know how it is caused，ask for advice，thank you！
```
<html>
<head>
<style>
.inputBorder {
			height: 15px;
			border: none;
			border-bottom: 1px dashed #2f2a2a;
		}
</style>
</head>
<body>
<input class="inputBorder" type="text" style="width: 80px;" readonly="readonly"
	   value="" />
</body>
</html>
```
```
java.lang.NullPointerException
	at com.openhtmltopdf.pdfboxout.PdfBoxFontResolver.resolveFont(PdfBoxFontResolver.java:85)
	at com.openhtmltopdf.layout.SharedContext.getFont(SharedContext.java:353)
	at com.openhtmltopdf.pdfboxout.PdfBoxPerDocumentFormState.getControlFont(PdfBoxPerDocumentFormState.java:99)
	at com.openhtmltopdf.pdfboxout.PdfBoxPerDocumentFormState.processControls(PdfBoxPerDocumentFormState.java:149)
	at com.openhtmltopdf.pdfboxout.PdfBoxSlowOutputDevice.processControls(PdfBoxSlowOutputDevice.java:286)
	at com.openhtmltopdf.pdfboxout.PdfBoxSlowOutputDevice.finish(PdfBoxSlowOutputDevice.java:918)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.writePDF(PdfBoxRenderer.java:710)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:509)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:414)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:396)
	at com.openhtmltopdf.freemarker.FreeMarkerGenerator.generatePDF(FreeMarkerGenerator.java:125)
	at com.openhtmltopdf.freemarker.FreeMarkerGenerator.generatePDF(FreeMarkerGenerator.java:75)
	at com.openhtmltopdf.freemarker.FreeMarkerGeneratorTest.testFreeMarkerGenerator(FreeMarkerGeneratorTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

```

**Comment by danfickle** [comment]
Hi @pipti, this is a known issue with form controls. See [this comment](https://github.com/danfickle/openhtmltopdf/issues/183#issuecomment-377203434) for a simple workaround.

**Comment by abozanona** [comment]
Hi @danfickle ,  Is there a way to ignore this exception during the PDF generation process?

**Comment by danfickle** [comment]
Hi @abozanona, did you try the workaround suggested?
