### ISSUE TITLE
race condition in XRLog/JDKXRLogger

### ISSUE THREAD

**Issue by syjer** [danfickle/openhtmltopdf#646]
We're having what seems to be a race condition in our tests, which run in parallel in different threads :

```
Caused by: java.lang.NullPointerException
	at com.openhtmltopdf.util.JDKXRLogger.getLogger(JDKXRLogger.java:103)
	at com.openhtmltopdf.util.JDKXRLogger.isLogLevelEnabled(JDKXRLogger.java:75)
	at com.openhtmltopdf.util.XRLog.log(XRLog.java:122)
	at com.openhtmltopdf.util.XRLog.log(XRLog.java:85)
	at com.openhtmltopdf.context.StyleReference.getStylesheets(StyleReference.java:253)
	at com.openhtmltopdf.context.StyleReference.setDocumentContext(StyleReference.java:102)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.setDocumentP(PdfBoxRenderer.java:319)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.setDocumentP(PdfBoxRenderer.java:292)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.<init>(PdfBoxRenderer.java:247)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.buildPdfRenderer(PdfRendererBuilder.java:67)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:42)
```

I will put up a test case which reproduces the problem

_Originally posted by @testinfected in https://github.com/danfickle/openhtmltopdf/issues/552#issuecomment-775205782_

**Comment by syjer** [comment]
Thanks to @testinfected :+1: .

Code for reproducing the error:

```java
public static void main(String[] args) throws Exception {

        int p = 20;
        CountDownLatch latch = new CountDownLatch(p);
        for (int i = 0; i < p;i++) {
            new Thread(() -> {
                latch.countDown();
                try {
                    latch.await();
                    XRLog.log(Level.SEVERE, LogMessageId.LogMessageId0Param.CASCADE_IS_ABSOLUTE_CSS_UNKNOWN_GIVEN);
                } catch (InterruptedException e) {
                }
            }).start();
        }
    }
```

**Comment by syjer** [comment]
seems that moving https://github.com/danfickle/openhtmltopdf/blob/801780ba03537d004b3423485a3ac7692a09bb95/openhtmltopdf-core/src/main/java/com/openhtmltopdf/util/JDKXRLogger.java#L111

after the call `initializeJDKLogManager()` is enough to fix it. And it may make sense :).

We could even wrap the `initializeJDKLogManager` in a try {} block and setting the variable in a finally block.
