### ISSUE TITLE
Problem with embedded fonts and PDF/A generation

### ISSUE THREAD

**Issue by baedorf** [danfickle/openhtmltopdf#654]
I try to embedded/use fonts using your AutoFont example with Noto Sans in scanned directory.
Times-Roman and Times-Bold are listed in font properties in Foxit Phantom PDF.
How can I find which elments in HTML causes the usage of this fonts?

In inline css I use 
```
body {
    font-family:'Noto Sans';
}
```

I even try to generate a PDF/A compliant document and always get 
```

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at com.openhtmltopdf.pdfboxout.PdfBoxFastOutputDevice.drawString(PdfBoxFastOutputDevice.java:393)
	at com.openhtmltopdf.pdfboxout.PdfBoxTextRenderer.drawString(PdfBoxTextRenderer.java:52)
	at com.openhtmltopdf.render.AbstractOutputDevice.drawText(AbstractOutputDevice.java:101)
	at com.openhtmltopdf.render.InlineText.paint(InlineText.java:171)
	at com.openhtmltopdf.render.InlineLayoutBox.paintInline(InlineLayoutBox.java:279)
	at com.openhtmltopdf.render.simplepainter.SimplePainter.paintInlineContent(SimplePainter.java:170)
	at com.openhtmltopdf.render.simplepainter.SimplePainter.paintLayer(SimplePainter.java:72)
	at com.openhtmltopdf.render.PageBox.paintMarginAreas(PageBox.java:430)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.paintPageFast(PdfBoxRenderer.java:882)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.writePDFFast(PdfBoxRenderer.java:619)
```

Any ideas?

Remarks:
I use stlyes shown on Page Featutes wiki page.
I suppose I have to set font-family in any matcher (@Page..)
Is this correct?

**Comment by danfickle** [comment]
Yes, unfortunately that is correct. I plan to fix this with fall-back fonts (#641).

**Comment by baedorf** [comment]
I think I would be an alternative or better to define a default font family and not "only" a fallback.
This default font should be used if no css defines another font family

**Comment by jochenberger** [comment]
We should at least report a more helpful error to help people find the actual problem.
