### ISSUE TITLE
SVG with text not generated

### ISSUE THREAD

**Issue by dweil** [danfickle/openhtmltopdf#676]
This simple SVG is not generated by open2HTml. 
```
<!DOCTYPE html>
<html>
<body>

<svg height="90" width="200">
  <text x="10" y="20" style="fill:red;">Several lines:
    <tspan x="10" y="45">First line.</tspan>
    <tspan x="10" y="70">Second line.</tspan>
  </text>
  Sorry, your browser does not support inline SVG.
</svg>
 
</body>
</html>
```

Here is the sample code I use to generate pdf(it works when SVG does not contain text):
```
public static void openHtml2Pdf(File htmlFile, File pdfFile) throws IOException {
      try (OutputStream os = new FileOutputStream(pdfFile)) {
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.useFastMode();
            builder.useSVGDrawer(new BatikSVGDrawer());
            builder.withFile(htmlFile);
            builder.toStream(os);
            builder.run();
      }
}
```

**Comment by danfickle** [comment]
Hi @dweil,

I'm a bit late here but you could try with the correct `xmlns` attribute on the svg: `xmlns="http://www.w3.org/2000/svg"`. This is covered in the wiki.

**Comment by dweil** [comment]
Hi @danfickle , thanks for your answer. Your advice works and it was actually writen in the wiki.
The issue is I'm using foreign object which are "SVG2" and it seems that openhtmltpdf (or the library Batik you are using)  is not compatible with SVG2. Is there any hope?

Below is my call stack : 
`Exception in thread "main" org.w3c.dom.DOMException: The current document is unable to create an element of the requested type (namespace: http://www.w3.org/2000/svg, name: foreignobject).
	at org.apache.batik.dom.AbstractNode.createDOMException(AbstractNode.java:408)
	at org.apache.batik.anim.dom.SVGDOMImplementation.createElementNS(SVGDOMImplementation.java:203)
	at org.apache.batik.anim.dom.SVGOMDocument.createElementNS(SVGOMDocument.java:373)
	at org.apache.batik.dom.AbstractDocument.importNode(AbstractDocument.java:348)
	at org.apache.batik.dom.AbstractDocument.importNode(AbstractDocument.java:326)
	at org.apache.batik.dom.AbstractDocument.importNode(AbstractDocument.java:426)
	at org.apache.batik.dom.AbstractDocument.importNode(AbstractDocument.java:326)
	at com.openhtmltopdf.svgsupport.BatikSVGImage.drawSVG(BatikSVGImage.java:218)
	at com.openhtmltopdf.pdfboxout.PdfBoxSVGReplacedElement.paint(PdfBoxSVGReplacedElement.java:70)
	at com.openhtmltopdf.pdfboxout.PdfBoxFastOutputDevice.paintReplacedElement(PdfBoxFastOutputDevice.java:275)
	at com.openhtmltopdf.render.displaylist.DisplayListPainter.paintReplacedElement(DisplayListPainter.java:169)
	at com.openhtmltopdf.render.displaylist.DisplayListPainter.paintReplacedElements(DisplayListPainter.java:151)
	at com.openhtmltopdf.render.displaylist.DisplayListPainter.paint(DisplayListPainter.java:268)
	at com.openhtmltopdf.render.displaylist.DisplayListPainter.paintInlineContent(DisplayListPainter.java:130)
	at com.openhtmltopdf.render.displaylist.DisplayListPainter.paint(DisplayListPainter.java:262)
	at com.openhtmltopdf.render.displaylist.DisplayListPainter.paintInlineContent(DisplayListPainter.java:130)
	at com.openhtmltopdf.render.displaylist.DisplayListPainter.paint(DisplayListPainter.java:262)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.paintPageFast(PdfBoxRenderer.java:921)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.writePDFFast(PdfBoxRenderer.java:617)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPdfFast(PdfBoxRenderer.java:554)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:480)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:417)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:399)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:46)
	at com.stimulus.misc.TestHtmlToPdf.openhtmlToPdf(TestHtmlToPdf.java:55)`

**Comment by danfickle** [comment]
Hi @dweil,

Probably no hope. It seems even the browsers don't support all of SVG 2 and Batik definitely does not. Perhaps, depending on the SVG 2 features used, you could register a DOM manipulator and change them to SVG 1.1?
