### ISSUE TITLE
RENAMED: No timeouts for http, https protocols.

### ISSUE THREAD

**Issue by gengzi** [danfickle/openhtmltopdf#700]
Hello, there's a problem with using it now. We convert HTML to PDF. When we embed HTML image links and can't access them correctly, the thread will be blocked. This error will be reported once in half a hour or twice. Even if we can't get the modified image, we will convert PDF.

I want to know, if get picture error, will the current thread block? Are there any parameters that can be controlled? Please let me know

thanks  

```java
Cant't read image file ; unexpected problem for URI  'http://xxxx'
java.io.IOException: Unrecognized Image format
	at com.openhtmltopdf.pdfboxout.PdfBoxImage.<init>(PdfBoxImage.java:54)
	at com.openhtmltopdf.pdfboxout.PdfBoxUserAgent.getImageResource(PdfBoxUserAgent.java:99)
	at com.openhtmltopdf.pdfboxout.PdfBoxReplacedElementFactory.createReplacedElement(PdfBoxReplacedElementFactory.java:79)
	at com.openhtmltopdf.render.BlockBox.createReplaced(BlockBox.java:730)
	at com.openhtmltopdf.render.BlockBox.calcDimensions(BlockBox.java:854)
	at com.openhtmltopdf.render.BlockBox.calcDimensions(BlockBox.java:830)
	at com.openhtmltopdf.render.BlockBox.collapseBottomMargin(BlockBox.java:1415)
	at com.openhtmltopdf.render.BlockBox.collapseBottomMargin(BlockBox.java:1438)
	at com.openhtmltopdf.render.BlockBox.collapseBottomMargin(BlockBox.java:1438)
	at com.openhtmltopdf.render.BlockBox.collapseBottomMargin(BlockBox.java:1438)
	at com.openhtmltopdf.render.BlockBox.collapseMargins(BlockBox.java:1336)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:996)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:947)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:321)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:299)
	at com.openhtmltopdf.layout.BlockBoxing.layoutContent(BlockBoxing.java:90)
	at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:1178)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:1032)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:947)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.layout(PdfBoxRenderer.java:335)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:40)
```

**Comment by danfickle** [comment]
Currently the default protocol handler is very simple. It just uses `new URL(...).openStream()`. The docs inform us that this is likely to result in a default `HttpUrlConnection`. I tried the following code:

````java
package com.example;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;

public class App13 {
  public static void main(String... args) throws IOException {
    HttpURLConnection http = (HttpURLConnection) new URL("https://openhtmltopdf.com/").openConnection();
    System.out.println("READ: " + http.getReadTimeout());
    System.out.println("CONNECT: " + http.getConnectTimeout());
  }
}
````
Both reported zero, which the javadoc says means no timeout. So if you are calling out to a dodgy server it can cause a denial-of-service.

We probably need to set a reasonable timeout (any suggestions). In the meantime it is very easy to plug in your own protocol handler. I'd recommend using a more modern http library as shown in the integration guide on the wiki. If you wanted to keep using Java's old http API it could look something like this:

````java
public static class MyHttpStream implements FSStream {
  private InputStream strm;
  
  public DefaultHttpStream(InputStream strm) {
    this.strm = strm;
  }
  
  @Override
  public InputStream getStream() {
    return this.strm;
  }

  @Override
  public Reader getReader() {
    if (this.strm != null) {
      return new InputStreamReader(this.strm, StandardCharsets.UTF_8);
    }
    return null;
  }
}

public static class MyHttpStreamFactory implements FSStreamFactory {
  @Override
  public FSStream getUrl(String uri) {
      InputStream is = null;
  
      try {
          URL url = new URL(uri);
          URLConnection conn = url.openConnection();
          conn.setConnectTimeout(5_000 /* milliseconds */);
          conn.setReadTimeout(10_000 /* milliseconds */);
          conn.connect();
          is = conn.getInputStream();
      } catch (java.net.MalformedURLException e) {
          // log
      } catch (java.io.FileNotFoundException e) {
          // log
      } catch (java.io.IOException e) {
          // log
      }
      return new MyHttpStream(is);
  }
}

// Use on builder
builder.useProtocolsStreamImplementation(new MyHttpStreamFactory(), "http", "https");
````

Also consider whether you need to use a cache, especially if the server is not under your control.

**Comment by gengzi** [comment]
OK, thank you for your answer
