### ISSUE TITLE
Is there a way to output an image file rather than a pdf?

### ISSUE THREAD

**Issue by Jo3McCarthy** [danfickle/openhtmltopdf#73]
Hi, All;  

I think the process of rendering has some interim processing steps where content is converted into images.  Is there a method to output the images directly?  Or, could you please point me to a  point in the code where I could implement that function?

Thanks,

Jo3

**Comment by danfickle** [comment]
Hi @Jo3McCarthy 

There is a Java2D output device in the core. See the swing package I think. Unfortunately, it is broken at the moment. Also see #63 
If you'd like to work on it, I'd be happy to help. I think as a start we should work on moving it to its own module.

Regards,
Daniel.

**Comment by rototor** [comment]
Just saw this issue. With #74 I started to implement something similar to the PdfRendererBuilder. If you just want to quick render some HTML as Image you could use Graphics2DRenderer.renderToImageAutoSize(). But you need a URL (e.g. file.toURL().toExternalURI()) for that to work. With the Java2DRendererBuilder (name can still change) you can also render in memory HTML string as image. In the midterm I think we should get rid of the old Graphics2DRenderer and Java2DRenderer. The later does not even work at the moment.

**Comment by danfickle** [comment]
OK, I've implemented a new renderer and worked on the builder by @rototor (in a copy) to output to paged images. One can incorporate the java2d sub-module and use it thus (but it is likely to change):
````java
		BufferedImage bf = new BufferedImage(1, 1, BufferedImage.TYPE_3BYTE_BGR);
		final Graphics2D g2d = bf.createGraphics();
		
		Java2DRendererBuilder builder = new Java2DRendererBuilder();
		
		builder.withUri("file:///Users/me/Documents/pdftests/image-output-device-test.htm");
		builder.useLayoutGraphics(g2d);
		builder.usePageProcessor(new DefaultPageProcessor("/Users/me/Documents/pdftests/images/%page-number%.png"));
		builder.useSVGDrawer(new BatikSVGDrawer());
		
		Java2DRenderer renderer = builder.buildJava2DRenderer();
		
		renderer.layout();
		renderer.writePages(0);

		g2d.dispose();


````

which will output a PNG image for each page of the document in the correct size.

**Comment by danfickle** [comment]
Start of a checklist for the Java2D (or any new) output device:
+ [x] Output simple raster images
+ [x] Output simple SVG images (with no text or embedded images)
+ [ ] Output raster images referenced by data URIs.
+ [x] Import font-face rule fonts.
+ [ ] Test font fallback including in justified text.
+ [ ] Test font-face rule fonts in SVG images.
+ [ ] Test embedded raster images inside SVG images.
+ [ ] Correct RTL and BIDI support.
+ [x] Should default background color be white?

**Comment by Jo3McCarthy** [comment]
Thank you all for the input.  Your suggestions have led to a partial solution, but I have mutually exclusive requirements at the moment.  I can use the Graphics2DRenderer.renderToImageAutoSize() to render some of an image, but as I mentioned in Issue #71 the content I receive has HTML Entities from HTML5 (like "\&nbsp;" and such).  So, although I can use jsoup to parse the URL to a Document, I can not then feed that Document into Graphics2DRenderer.renderToImageAutoSize() because it requires a URL.  By hand-tweaking the content before rendering, I get the full image at the requested size.  But, hand-tweaking will not suffice for the use case.  If anybody has already encountered this and has a solution, please share.  Otherwise, I may have to go into the Graphics2DRenderer and implement another method that supports my requirement -- in which case, pray for me...

**Comment by danfickle** [comment]
RC10 has been released with image output in alpha state.
Current limitations:
+ RTL is not supported properly.
+ <s>Custom object drawer support not implemented.</s> Implemented in RC11.
+ Font fallback is not implemented for justified text.
+ Fonts can only be specified via font-face rules and not the builder.

The [builder code can be found here](https://github.com/danfickle/openhtmltopdf/blob/open-dev-v1/openhtmltopdf-java2d/src/main/java/com/openhtmltopdf/java2d/api/Java2DRendererBuilder.java).

You'll also need to include the Java2D submodule:
````xml
<dependency>
  		<groupId>com.openhtmltopdf</groupId>
  		<artifactId>openhtmltopdf-java2d</artifactId>
  		<version>${openhtml.version}</version>
  	</dependency>
````
Here is a simple example:
````java
		DefaultPageProcessor processor = new DefaultPageProcessor(new FSPageOutputStreamSupplier() {
			@Override
			public OutputStream supply(int zeroBasedPageNumber) throws IOException {
				return new FileOutputStream("/Users/you/Documents/pdftests/images/%page-number%.png".replace("%page-number%", String.valueOf(zeroBasedPageNumber)));
			}
		}, BufferedImage.TYPE_3BYTE_BGR, "png");
		
		Graphics2D g2d = processor.createLayoutGraphics();
		
		Java2DRendererBuilder builder = new Java2DRendererBuilder();
		builder.withUri("file:///Users/you/Documents/pdftests/showcase.htm");
		builder.useLayoutGraphics(g2d);
		builder.useSVGDrawer(new BatikSVGDrawer()); // Optional
		builder.toPageProcessor(processor);
		builder.runPaged();

		g2d.dispose();
````

**Comment by danfickle** [comment]
I think this is the correct place to note that the layout for continuous image output mode is using "print" rather than "screen" media. This should be set by the builder, probably on the ````SharedContent```` object.

**Comment by conlaoch1** [comment]
hi @danfickle , thanks for the image feature! i do have one problem when calling `java2DRendererBuilder.runFirstPage()`.
It looks like its missing a font at the very last string of the html template, but i can't get my head around why.

`java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[na:na]
	at java.base/java.util.Objects.checkIndex(Objects.java:372) ~[na:na]
	at java.base/java.util.ArrayList.get(ArrayList.java:458) ~[na:na]
	at com.openhtmltopdf.java2d.Java2DTextRenderer.getWidth(Java2DTextRenderer.java:294) ~[openhtmltopdf-java2d-1.0.3.jar:na]
	at com.openhtmltopdf.layout.Breaker.doBreakText(Breaker.java:432) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.layout.Breaker.doBreakText(Breaker.java:209) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.layout.Breaker.breakText(Breaker.java:119) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.layout.InlineBoxing.layoutText(InlineBoxing.java:1083) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.layout.InlineBoxing.startInlineText(InlineBoxing.java:388) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.layout.InlineBoxing.layoutContent(InlineBoxing.java:186) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.render.BlockBox.layoutInlineChildren(BlockBox.java:1220) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:1201) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:1058) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:973) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:321) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:299) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.layout.BlockBoxing.layoutContent(BlockBoxing.java:90) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:1204) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:1058) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:973) ~[openhtmltopdf-core-1.0.3.jar:na]
	at com.openhtmltopdf.java2d.Java2DRenderer.layout(Java2DRenderer.java:252) ~[openhtmltopdf-java2d-1.0.3.jar:na]
	at com.openhtmltopdf.java2d.api.Java2DRendererBuilder.runFirstPage(Java2DRendererBuilder.java:108) ~[openhtmltopdf-java2d-1.0.3.jar:na]`

**Comment by conlaoch1** [comment]
hi, @danfickle. the created image has a very low resolution / is very pixelated. is there a way to up the quality? thanks!

```java
File file = new File("test");
            DefaultPageProcessor processor = new DefaultPageProcessor(new FSPageOutputStreamSupplier() {
                @Override
                public OutputStream supply(int zeroBasedPageNumber) throws IOException {
                    return new FileOutputStream(file);
                }
            }, BufferedImage.TYPE_3BYTE_BGR, "png");

            Graphics2D g2d = processor.createLayoutGraphics();

            Java2DRendererBuilder java2DRendererBuilder = new Java2DRendererBuilder();
            java2DRendererBuilder.withHtmlContent(filledOutTemplate, PDFUtil.class.getResource("/fonts/").toExternalForm() + "../");;
            java2DRendererBuilder.useEnvironmentFonts(true);
            java2DRendererBuilder.useLayoutGraphics(g2d);
            java2DRendererBuilder.useFastMode();
            java2DRendererBuilder.buildJava2DRenderer();
            java2DRendererBuilder.toPageProcessor(processor);
            java2DRendererBuilder.runFirstPage();

            g2d.dispose();
```
