### ISSUE TITLE
NPE when creating a PDF from html with usePdfUaAccessbility true

### ISSUE THREAD

**Issue by dganeshb** [danfickle/openhtmltopdf#804]
While trying to generate an Accessible document from html I get a warning  followed by a NPE exception:

com.openhtmltopdf.general WARNING:: Trying to add incompatible child to parent item:  child type=GenericStructualElement, parent type=ListStructualElement, expected child type=ListItemStructualElement. Document will not be PDF/UA compliant.

java.lang.NullPointerException
	at org.apache.pdfbox.cos.COSArray.add(COSArray.java:62)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.finishNumberTree(PdfBoxAccessibilityHelper.java:858)
	at com.openhtmltopdf.pdfboxout.PdfBoxFastOutputDevice.finish(PdfBoxFastOutputDevice.java:908)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.writePDFFast(PdfBoxRenderer.java:674)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPdfFast(PdfBoxRenderer.java:564)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:490)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:427)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:409)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:46)

This is the code snippet I use

            PdfRendererBuilder  builder = new PdfRendererBuilder();
            builder.useFastMode();
            builder.usePdfUaAccessbility(true);
            builder.toStream(outputStream);
            
            Matcher m = unescapedAmpersands.matcher(rawHtml);
            String cleanHtml = m.replaceAll("&amp;");
            cleanHtml = cleanHtml.replace("\\","/");
            cleanHtml = cleanHtml.replace("src=\"","src=\"file:///");
            System.out.println(cleanHtml);
            builder.withHtmlContent(cleanHtml, "/");
            //builder.withW3cDocument(xhtml,"/");
            String fontpath = USER_DIR+"/src/main/resources/META-INF/resources/fonts/";
            File calibriFile = new File(fontpath+"Calibri.ttf");
            File calibriBoldFile = new File(fontpath+"CalibriBold.ttf");
            File calibriBoldItalicFile = new File(fontpath+"CalibriBoldItalic.ttf");
            
            builder.useFont(calibriFile, Font.createFont(Font.TRUETYPE_FONT, calibriFile).getFamily());
            builder.useFont(calibriFile, "Calibri sans-serif");
            builder.useFont(calibriBoldFile, "Calibri sans-serif", 700, FontStyle.NORMAL, true);
            builder.useFont(calibriBoldItalicFile, Font.createFont(Font.TRUETYPE_FONT, calibriBoldItalicFile).getFamily(), 700, FontStyle.ITALIC, true);
            builder.useFont(calibriFile, "Serif");
  
           
            builder.run();

The html content is attached
[pdfBox.txt](https://github.com/danfickle/openhtmltopdf/files/7999026/pdfBox.txt)

If the usePdfUaAccessbility is not set it creates the pdf document
I am unable to debug what portion of the attached  html is causing this issue. Please help

**Comment by dganeshb** [comment]
Html had a issue. Sorry closing it
