### ISSUE TITLE
NPE in InlineBoxing.layoutContent(...)

### ISSUE THREAD

**Issue by jansorg** [danfickle/openhtmltopdf#82]
I tried to switch from flyinsaucer to openhtmltopdf rc10. The rendering threw an NPE.
rc5 works with the rendering, I tested rc10, rc9 and rc7 (which all throw the NPE).

```
null
java.lang.NullPointerException
	at com.openhtmltopdf.layout.InlineBoxing.layoutContent(InlineBoxing.java:64)
	at com.openhtmltopdf.render.BlockBox.layoutInlineChildren(BlockBox.java:1001)
	at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:982)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:865)
	at com.openhtmltopdf.newtable.TableRowBox.layoutCell(TableRowBox.java:453)
	at com.openhtmltopdf.newtable.TableRowBox.layoutChildren(TableRowBox.java:206)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:865)
	at com.openhtmltopdf.newtable.TableRowBox.layout(TableRowBox.java:89)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:794)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:321)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:299)
	at com.openhtmltopdf.layout.BlockBoxing.layoutContent(BlockBoxing.java:90)
	at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:985)
	at com.openhtmltopdf.newtable.TableSectionBox.layoutChildren(TableSectionBox.java:139)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:865)
	at com.openhtmltopdf.newtable.TableSectionBox.layout(TableSectionBox.java:275)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:794)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:321)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:299)
	at com.openhtmltopdf.layout.BlockBoxing.layoutContent(BlockBoxing.java:90)
	at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:985)
	at com.openhtmltopdf.newtable.TableBox.layoutChildren(TableBox.java:311)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:865)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:794)
	at com.openhtmltopdf.newtable.TableBox.layoutTable(TableBox.java:277)
	at com.openhtmltopdf.newtable.TableBox.layout(TableBox.java:237)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:321)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:299)
	at com.openhtmltopdf.layout.BlockBoxing.layoutContent(BlockBoxing.java:90)
	at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:985)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:865)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:794)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:321)
	at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:299)
	at com.openhtmltopdf.layout.BlockBoxing.layoutContent(BlockBoxing.java:90)
	at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:985)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:865)
	at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:794)
	at com.openhtmltopdf.swing.RootPanel.doDocumentLayout(RootPanel.java:320)
	at com.openhtmltopdf.swing.BasicPanel.paintComponent(BasicPanel.java:142)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:165)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by danfickle** [comment]
Thanks @jansorg for bringing this to our attention. You wouldn't happen to have a minimal HTML example that triggers this? Either way, I'll try to have a look shortly.

**Comment by jansorg** [comment]
@danfickle Thanks for your feedback!
I reduced my html to a very minimal file and a small java program which creates the component. As soon as you resize that window it's going to throw that NPE.
(The invokeLater seems to be necessary because otherwise it's throwing a SharedContext exception)

```html
<html>
<body>

<table>
    <tr>
        <td>matplotlib.<span class="module-name">pyplot</span></td>
        <td class=" lower_opacity aligned_right">module</td>
    </tr>
</table>

</body>
</html>
```

```java
import com.openhtmltopdf.simple.XHTMLPanel;
import com.openhtmltopdf.util.XMLUtil;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.net.URISyntaxException;

public class TestBrowser {
    public static void main(String[] args) throws URISyntaxException, IOException {
        SwingUtilities.invokeLater(() -> {
            XHTMLPanel html = new XHTMLPanel();

            try {
                html.setDocument(XMLUtil.documentFromFile(args[0]));
            } catch (Exception e) {
                throw new RuntimeException(e);
            }

            JFrame frame = new JFrame("Demo");
            frame.setMinimumSize(new Dimension(200,200));
            frame.setLayout(new BorderLayout());
            frame.getContentPane().add(html);

            frame.pack();
            frame.setVisible(true);
        });
    }
}
```

**Comment by danfickle** [comment]
We no longer support the swing components so closing this now.
