### ISSUE TITLE
NullPointerException in only some environments

### ISSUE THREAD

**Issue by qingyanger** [danfickle/openhtmltopdf#826]
` Caused by: java.lang.NullPointerException: null
 at com.openhtmltopdf.pdfboxout.PdfBoxFontResolver$FontDescription.loadMetrics(PdfBoxFontResolver.java:614)
 at com.openhtmltopdf.pdfboxout.PdfBoxFontResolver$FontDescription.realizeFont(PdfBoxFontResolver.java:633)
 at com.openhtmltopdf.pdfboxout.PdfBoxFontResolver$FontDescription.getFont(PdfBoxFontResolver.java:679)
 at com.openhtmltopdf.pdfboxout.PdfBoxTextRenderer.getWidth(PdfBoxTextRenderer.java:347)
 at com.openhtmltopdf.render.InlineBox.getTextWidth(InlineBox.java:195)
 at com.openhtmltopdf.render.InlineBox.calcMinWidthFromWordLength(InlineBox.java:294)
 at com.openhtmltopdf.render.InlineBox.calcMinMaxWidth(InlineBox.java:420)
 at com.openhtmltopdf.render.BlockBox.calcMinMaxWidthInlineChildren(BlockBox.java:2027)
 at com.openhtmltopdf.render.BlockBox.calcMinMaxWidth(BlockBox.java:1920)
 at com.openhtmltopdf.newtable.TableBox$AutoTableLayout.recalcColumn(TableBox.java:1256)
 at com.openhtmltopdf.newtable.TableBox$AutoTableLayout.fullRecalc(TableBox.java:1230)
 at com.openhtmltopdf.newtable.TableBox$AutoTableLayout.calcMinMaxWidth(TableBox.java:1517)
 at com.openhtmltopdf.newtable.TableBox.calcMinMaxWidth(TableBox.java:162)
 at com.openhtmltopdf.newtable.TableBox.layout(TableBox.java:228)
 at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:388)
 at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:366)
 at com.openhtmltopdf.layout.BlockBoxing.layoutContent(BlockBoxing.java:106)
 at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:1284)
 at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:1085)
 at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:1028)
 at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:388)
 at com.openhtmltopdf.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:366)
 at com.openhtmltopdf.layout.BlockBoxing.layoutContent(BlockBoxing.java:106)
 at com.openhtmltopdf.render.BlockBox.layoutChildren(BlockBox.java:1284)
 at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:1085)
 at com.openhtmltopdf.render.BlockBox.layout(BlockBox.java:1028)
 at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.layout(PdfBoxRenderer.java:353)
 at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:45)`

**Comment by qingyanger** [comment]
is the problem of getting the font file path
