### ISSUE TITLE
images missing in created pdf?

### ISSUE THREAD

**Issue by hjs2457** [danfickle/openhtmltopdf#928]
im working on an app thats using this library. we have it set up to where a user sends an email from their phone and then our app will recieve it and make a pdf out of the entire contents of the body of the email. most email apps send images as attachments which is working perfectly in which a separate image file receipt will be generated for each attachment. but in the case of sending the email from iphone Mail app which always sends images as embedded in the body, the pdf result will have the text but the images are missing. QA says this feature used to work properly but i think like theyre either wrong or it used to work properly when they were using a different library. 
heres some of the log:
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=us-ascii">
</head>
<body dir="auto">
<br>
<br>
<div dir="ltr">Sent from my iPhone<img alt="image0.png" src="cid:B9631038-D3C7-4C0B-80D1-87003BAEE001-L0-001"></div>
</body>
</html>
 FLAGS (\Seen \Deleted \Recent))
A7 OK FETCH completed.
PDFUtil - cHTD start
java.lang.Exception: Stack trace
        at java.lang.Thread.dumpStack(Thread.java:1336)
        at largesoft.receipts.pdf.PDFUtil.convertHtmlToDocument(PDFUtil.java:117)
        at largesoft.receipts.html2pdf.DefaultHtml2PdfHandler.html2Pdf(DefaultHtml2PdfHandler.java:68)
        at largesoft.receipts.DownloadEmail.handleBodyPart(DownloadEmail.java:947)
        at largesoft.receipts.DownloadEmail.getAttachements(DownloadEmail.java:910)
        at largesoft.receipts.DownloadEmail.doEMailDownload(DownloadEmail.java:650)
        at largesoft.receipts.DownloadEmail.executeRequest(DownloadEmail.java:361)
        at largesoft.receipts.ReceiptsAttachmentBkg.processReceipts(ReceiptsAttachmentBkg.java:43)
        at largesoft.receipts.ReceiptsAttachmentBkg.freeWorkModel(ReceiptsAttachmentBkg.java:32)
        at largesoft.bkgproc.ServerBackgroundProcess.run(ServerBackgroundProcess.java:446)
2023-05-19 03:39:42,237 [ReceiptsAttachmentBkg] ERROR server  jsmith <HCMt70> PDFUtil - Failed to load preferred font: NotoSansCJKsc-Light.otf
java.lang.NullPointerException: null
        at largesoft.receipts.pdf.PDFUtil.getPreferredFont(PDFUtil.java:374) [extn-core.jar:?]
        at largesoft.receipts.pdf.PDFUtil.convertHtmlToDocument(PDFUtil.java:130) [extn-core.jar:?]
        at largesoft.receipts.html2pdf.DefaultHtml2PdfHandler.html2Pdf(DefaultHtml2PdfHandler.java:68) [extn-core.jar:?]
        at largesoft.receipts.DownloadEmail.handleBodyPart(DownloadEmail.java:947) [extn-server.jar:?]
        at largesoft.receipts.DownloadEmail.getAttachements(DownloadEmail.java:910) [extn-server.jar:?]
        at largesoft.receipts.DownloadEmail.doEMailDownload(DownloadEmail.java:650) [extn-server.jar:?]
        at largesoft.receipts.DownloadEmail.executeRequest(DownloadEmail.java:361) [extn-server.jar:?]
        at largesoft.receipts.ReceiptsAttachmentBkg.processReceipts(ReceiptsAttachmentBkg.java:43) [extn-server.jar:?]
        at largesoft.receipts.ReceiptsAttachmentBkg.freeWorkModel(ReceiptsAttachmentBkg.java:32) [extn-server.jar:?]
        at largesoft.bkgproc.ServerBackgroundProcess.run(ServerBackgroundProcess.java:446) [extn-server.jar:?]
com.openhtmltopdf.load INFO:: TIME: parse stylesheets 73ms
com.openhtmltopdf.match INFO:: media = print
com.openhtmltopdf.match INFO:: Matcher created with 160 selectors
com.openhtmltopdf.load INFO:: Loading font(PREFERRED_FONT) from PDFont supplier now.
com.openhtmltopdf.exception WARNING:: Bad URL given: cid:B9631038-D3C7-4C0B-80D1-87003BAEE001-L0-001 => java.net.MalformedURLException:: unknown protocol: cid
com.openhtmltopdf.exception WARNING:: Bad URL given: cid:B9631038-D3C7-4C0B-80D1-87003BAEE001-L0-001 => java.net.MalformedURLException:: unknown protocol: cid
com.openhtmltopdf.exception WARNING:: Bad URL given: cid:B9631038-D3C7-4C0B-80D1-87003BAEE001-L0-001 => java.net.MalformedURLException:: unknown protocol: cid

Does the null pointer exception about the font have anything to do with this? Or does this  "WARNING: Bad URL given" tell you anything important as to how I could possibly fix this?
I saw in another issue post someone said they got it working by adding a "temp folder" for the tomcat server, I checked with the team who say we already have a temp folder for the tomcat server.

Any help appreciated if theres nothing we can do then I will have to change to a different library. 
Thank you.

**Comment by costas80** [comment]
I had a similar issue in some cases and narrowed it down to how the image is added in the HTML. In my case the problem was linked to images with no defined width or height that were present within tables. Either removing them from tables or setting the width/height corrected the issue.

**Comment by hjs2457** [comment]
this is what the html is looking like from the email sent from my iphone
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=us-ascii">
</head>
<body dir="auto">
My receipts
<div><img alt="image0.jpeg" src="cid:E4589BA8-9032-4091-A47C-CF641AE45A64-L0-001"><br>
<br>
<div dir="ltr">Sent from my iPhone</div>
</div>
</body>
</html>

so seeing that the img is "<img alt="image0.jpeg" src="cid:E4589BA8-9032-4091-A47C-CF641AE45A64-L0-001">" are you saying that i could maybe manually add in width="" and height="" in there and that might make it work? im willing to try that but i feel like it has something to do with the "com.openhtmltopdf.exception WARNING:: Bad URL given: cid:E4589BA8-9032-4091-A47C-CF641AE45A64-L0-001 => java.net.MalformedURLException:: unknown protocol: cid" error message which i dont even know what that means.

**Comment by costas80** [comment]
Ah hang on - the problem I see is from the "cid" image sources not the width/height I had mentioned. This is what is also getting reported in the exceptions you get:

> WARNING:: Bad URL given: cid:B9631038-D3C7-4C0B-80D1-87003BAEE001-L0-001

When you use CID references these point to images that are attachments of emails. I assume these will not be able to be loaded through the library to add the image to your PDF. Possible ways to fix this that I can think of are:
* To replace the image source definitions in the email HTML with references to accessible remote URIs (or maybe data: content).
* To parse your emails and store each embedded/attached image in a temp directory, form where you would load the images by means of a URI resolver passed to the PDF generation (to map each CID reference to the image on the temp folder).

**Comment by hjs2457** [comment]
this must work on a deployment so i know idea 2 wont work. ive tried making temp files before and QA says it failed on their build (temp images are just not going to work at all in this case). do you think a different library (openpdf or something) would work? or no libraries is going to work. FYI email attachments are able to be saved as separate image files, but when the email is sent from iphone (when sending on iphone, images will not be attached, theyre always embedded in the body), the images will be missing. my supervisor suggested trying to use a different library which im beginning to think is not going to work either since it simply doesnt know how to load an image that was embedded in the body of an email, (how would a different library handle it better, it probably would not). there must be a way to get this working using this library.
please elaborate on idea 1: "To replace the image source definitions in the email HTML with references to accessible remote URIs (or maybe data: content)." because idea 2 with temp images is out of the question.
what do i do for idea 1?
thanks so much.

**Comment by costas80** [comment]
> do you think a different library (openpdf or something) would work?

OpenPDF takes a different approach to generating PDFs by using Java code (like iText). In my experience using a Java-based approach (OpenPDF/iText) or template-based report (JasperReports) is much more cumbersome than using HTML (this library). If you need to support any kind of user-provided HTML content in reports this library would be the way to go. Also, the core issue you are facing would be there regardless of which library you use as it relates to loading images that can't be retrieved.

> (how would a different library handle it better, it probably would not). there must be a way to get this working using this library.

Exactly. You'd have the same issue with any library. The approach I use (very successfully) with this library is to generate the report HTML using Freemarker templates that include "controlled" (predefined) HTML parts but also sections that are user-provided HTML. Both can include images provided by users. For user-provided images we use a custom `FSUriResolver` on the `PdfRendererBuilder` that translates the image paths to the actual image file locations (if these are not public image references). With this approach you would do something like this:
```java
var builder = new PdfRendererBuilder();
builder.useUriResolver(new NaiveUserAgent.DefaultUriResolver() {
    @Override
    public String resolveURI(String baseUri, String uri) {
        if (uri.startsWith("cid:")) {
            // Convert the CID reference to a file:// URI on your filesystem (a pointer to the extracted image on a temp folder).
            return resolvedUri;
        }
        // Default resolution for all other cases.
        return super.resolveURI(baseUri, uri);
    }
});
```
If you have access to the email and its attached/embedded images I don't see why you can't follow this approach.

> "To replace the image source definitions in the email HTML with references to accessible remote URIs (or maybe data: content)." because idea 2 with temp images is out of the question.

Seeing your use case I don't think you can go with replacing the image references as these are image attachments to emails. The option I would go for would be as follows (server-side):
1. Parse the email coming in and detect all embedded images.
2. Store each embedded image in a temp folder and keep somewhere the mapping between CID URL and temp file location.
3. Leave the HTML unchanged.
4. Via the custom URI resolver (see code above) tell the library where to find each image.

**Comment by hjs2457** [comment]
thank you so much this is very helpful. i know how to grab the embedded images from the email and save them, but im trying to draw something on the pdf thats saved to the file system?
PdfRendererBuilder builder = new PdfRendererBuilder();
builder.useUriResolver(new NaiveUserAgent.DefaultUriResolver() {
	@Override
	public String resolveURI(String baseUri, String uri) {
		System.out.println("baseuri "+baseUri);
		System.out.println("uri "+uri);
		if (uri.startsWith("cid:")) {
			System.out.println("uri starts with cid:");
			File f = new File("blue1.png");
			System.out.println("f exists"+f.exists());
			// Convert the CID reference to a file:// URI on your filesystem (a pointer to the extracted image on a temp folder).
			String resolvedUri;
			resolvedUri = "blue1.png";
			return resolvedUri;
		}
		return super.resolveURI(baseUri, uri);
	}
});

in this code the f exists outputs to true, but when i return resolvedUri = blue1.png it does not get drawn? what am i missing here? is something else supposed to be in this resolvedUri variable? thanks so much again this has been extremely helpful.

**Comment by costas80** [comment]
Happy to help out :)

The `resolveURI` method needs to return a URI, not just a file name or path. You need to change your code as follows:
```java
PdfRendererBuilder builder = new PdfRendererBuilder();
builder.useUriResolver(new NaiveUserAgent.DefaultUriResolver() {
   @OverRide
   public String resolveURI(String baseUri, String uri) {
      if (uri.startsWith("cid:")) {
         // Convert the CID reference to a file:// URI on your filesystem (a pointer to the extracted image on a temp folder).
         return new File("blue1.png").toURI().toString()
      }
      return super.resolveURI(baseUri, uri);
   }
});
```
You were missing the `toURI()` on the file. The string representation of the URI will add the `file://` prefix and correctly adapt any directory paths needed.

**Comment by hjs2457** [comment]
thanks. i have it generating a pdf with text, then image, then text, for the first time ever! however the image is not the image that was sent from my iphone its just a test image. i also have the code thats saving all the embedded images from the email. the problem im facing now is that the code that is saving the image files happens AFTER the uri resolver is supposed to use them so the image files get saved successfully but when i try to tell it to draw the image using the new saved image (instead of the test image) it doesnt find it, and then it gets saved right after. any idea on how i could resolve this?
public static void convertHtmlToDocument(InputStream in, OutputStream out, URI baseUri) throws IOException
	{
		System.out.println("PDFUtil - cHTD start");
		System.out.println("in "+in);
		String currentPath = new java.io.File(".").getCanonicalPath();
		org.jsoup.nodes.Document jsoupDoc = Jsoup.parse(in, "utf8", baseUri.toString());
		// Overrides font for all elements so preferred font can be applied.
		jsoupDoc.select("*").forEach(elem -> {
			String style = elem.attr("style");
			elem.attr("style", style + "font-family:" + PREFERRED_FONT_FAMILY);
		});
		
		W3CDom w3c = new W3CDom();
		org.w3c.dom.Document w3cDoc = w3c.fromJsoup(jsoupDoc);

		PdfRendererBuilder builder = new PdfRendererBuilder();
		builder.useUriResolver(new NaiveUserAgent.DefaultUriResolver() {
			@Override
			public String resolveURI(String baseUri, String uri) {
				if (uri.startsWith("cid:")) {
					// Convert the CID reference to a file:// URI on your filesystem (a pointer to the extracted image on a temp folder).
					String resuri;
					//resuri = new File("blue1.png").toURI().toString();
					File f = new File(System.getProperty("user.dir")+"/html2pdf/temp/tn1.png");
					File f2 = new File(System.getProperty("user.dir")+"/html2pdf/temp/part1.jpeg");
					System.out.println("f2 exists "+f2.exists());
					resuri = f.toURI().toString();
					System.out.println("resuri "+resuri);
					return resuri;
				}
				return super.resolveURI(baseUri, uri);
			}
		});
		builder.useFont(new PDFontSupplier(getPreferredFont()), PREFERRED_FONT_FAMILY);
		builder.useFastMode();
		builder.withW3cDocument(w3cDoc, baseUri.toString());
		builder.toStream(out);
		builder.run();
	}

the in variable is a ByteArrayInputStream so im thinking the images are in that data structure somewhere

**Comment by hjs2457** [comment]
thank you so much. i have it set up to where now the images are in the pdf. the image files are temporarily saved and then deleted after the uri resolver uses them. so im sending 2 new datastructures which are an arraylist for the images and an arraylist for the "old uris" so the uri resolver knows which image goes with which uri. only problem is the images (taken on my iphone camera) show up rotated 90 degrees to the left. i had this problem with my "bad solution" where i was drawing the images onto the pdf manually which ended up not satisfying our needs. but the way i dealt with the rotation was literally reading the orientation using its metadata which required another library and then applying an affinetransform rotation to the pdf graphics object to then draw it on rotated properly which also messes up the orientation so i had to move the orientation correctly which was complicated. the whole point is that i know why the image is rotated but not sure what the right approach is here. is there a PdfRendererBuild method that i can tell it to draw the image with a rotation or does this problem need to be addressed when saving the temporary image in the first place?

**Comment by costas80** [comment]
Well, everything here is driven by CSS so maybe if you try using the `rotate()` function it will work?
```
img.rotated {
    transform: rotate(90deg);
}
```
Otherwise you could pre-rotate your temporarily stored images before the PDF generation using plain java.

**Comment by m-ovs** [comment]
Hello. I've also have this bug with images. I've got this error 
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper$AbstractTreeItem.finish(com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper$AbstractStructualElement)" because "item" is null
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.finishTreeItem(PdfBoxAccessibilityHelper.java:905)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.access$800(PdfBoxAccessibilityHelper.java:43)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper$FigureStructualElement.finish(PdfBoxAccessibilityHelper.java:750)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.finishTreeItems(PdfBoxAccessibilityHelper.java:900)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.access$400(PdfBoxAccessibilityHelper.java:43)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper$GenericStructualElement.finish(PdfBoxAccessibilityHelper.java:262)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.finishTreeItems(PdfBoxAccessibilityHelper.java:900)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.access$400(PdfBoxAccessibilityHelper.java:43)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper$GenericStructualElement.finish(PdfBoxAccessibilityHelper.java:255)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.finishTreeItems(PdfBoxAccessibilityHelper.java:900)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.access$400(PdfBoxAccessibilityHelper.java:43)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper$TableCellStructualElement.finish(PdfBoxAccessibilityHelper.java:701)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.finishTreeItems(PdfBoxAccessibilityHelper.java:900)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.access$400(PdfBoxAccessibilityHelper.java:43)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper$TableRowStructualElement.finish(PdfBoxAccessibilityHelper.java:617)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.finishTreeItems(PdfBoxAccessibilityHelper.java:900)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.access$400(PdfBoxAccessibilityHelper.java:43)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper$TableBodyStructualElement.finish(PdfBoxAccessibilityHelper.java:567)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.finishTreeItems(PdfBoxAccessibilityHelper.java:900)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.access$400(PdfBoxAccessibilityHelper.java:43)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper$TableStructualElement.finish(PdfBoxAccessibilityHelper.java:515)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.finishTreeItems(PdfBoxAccessibilityHelper.java:900)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.access$400(PdfBoxAccessibilityHelper.java:43)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper$GenericStructualElement.finish(PdfBoxAccessibilityHelper.java:262)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.finishTreeItems(PdfBoxAccessibilityHelper.java:900)
	at com.openhtmltopdf.pdfboxout.PdfBoxAccessibilityHelper.finishPdfUa(PdfBoxAccessibilityHelper.java:841)
	at com.openhtmltopdf.pdfboxout.PdfBoxFastOutputDevice.finish(PdfBoxFastOutputDevice.java:895)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.writePDFFast(PdfBoxRenderer.java:674)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPdfFast(PdfBoxRenderer.java:564)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:490)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:427)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:409)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:46)
	at com.dbeaver.htmltopdf.Main.main(Main.java:40)
Disconnected from the target VM, address: '127.0.0.1:44120', transport: 'socket'
```

I discovered that the problem is when the image appears in the table cell, but ony if there is a text before the image in the same cell. 

```
<table>
<tr><td><img  alt="text" src="/Button.png"></td></tr> // OK
<tr><td>.<img  alt="text" src="/Button.png">.</td></tr> // Error
</table>
```


This is obviusly the bug, somehow we cann't read the image dimentions in that case. Setting up the dimentions in the code helps.
I tried to set it up in css like this
`table td img {min-width:1px;min-height:1px;}`
But I got 1x1 image in the pdf in that case.
